name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and push image

    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v5

      - name: Install Encore
        run: |
          curl -L https://encore.dev/install.sh | bash
          echo "~/.encore/bin" >> $GITHUB_PATH

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: "ghcr.io"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        run: encore build docker ghcr.io/jonahsnider/stars.jonahsnider.com

      - name: Push image
        run: docker push ghcr.io/jonahsnider/stars.jonahsnider.com:latest
